name: Linters

on: push

jobs:
  linters:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v3.1.1
        with:
          python-version: 3.9

      - name: Setup poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python - && echo "$HOME/.poetry/bin" >> $GITHUB_PATH

      - name: Running mypy
        run: |
          poetry run mypy myproject

      - name: Super-Linter
        uses: github/super-linter@v4.9.2
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
